CREATE TABLE `city` (
  `idCity` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `population` int(11) DEFAULT NULL,
  PRIMARY KEY (`idCity`)
) 

insert into city (name, population) values ('Qingdao', 885.32);
insert into city (name, population) values ('Ananindeua', 310.51);
insert into city (name, population) values ('Jinfeng', 963.12);
insert into city (name, population) values ('Malishka', 136.14);
insert into city (name, population) values ('Szombathely', 304.93);
insert into city (name, population) values ('Montecarlo', 878.95);
insert into city (name, population) values ('Dobroměřice', 756.91);
insert into city (name, population) values ('São Lourenço do Sul', 235.6);
insert into city (name, population) values ('Washington', 730.81);
insert into city (name, population) values ('Ulricehamn', 741.6);
insert into city (name, population) values ('Stakhanov', 13.25);
insert into city (name, population) values ('Gromnik', 98.39);
insert into city (name, population) values ('Maoming', 309.32);
insert into city (name, population) values ('Planá', 313.11);
insert into city (name, population) values ('Jinli', 929.33);
insert into city (name, population) values ('Yemva', 932.77);
insert into city (name, population) values ('Caba', 52.68);
insert into city (name, population) values ('Omiš', 33.48);
insert into city (name, population) values ('Pasirhuni', 167.28);
insert into city (name, population) values ('Ondores', 314.51);
insert into city (name, population) values ('Tegalagung', 282.68);
insert into city (name, population) values ('Elefsína', 586.2);
insert into city (name, population) values ('Maoping', 723.69);
insert into city (name, population) values ('Xingquan', 306.88);
insert into city (name, population) values ('Sanxing', 198.84);
insert into city (name, population) values ('Nowe Miasto', 808.56);
insert into city (name, population) values ('Xingou', 367.19);
insert into city (name, population) values ('Veghel', 380.84);
insert into city (name, population) values ('Martil', 271.35);
insert into city (name, population) values ('Luleå', 543.61);
insert into city (name, population) values ('Zelenodolsk', 88.43);
insert into city (name, population) values ('Jaffna', 481.19);
insert into city (name, population) values ('Mamponteng', 168.79);
insert into city (name, population) values ('Barberena', 469.86);
insert into city (name, population) values ('Asahbadung', 985.16);
insert into city (name, population) values ('Altamira', 939.7);
insert into city (name, population) values ('Junín', 157.63);
insert into city (name, population) values ('Drawsko Pomorskie', 202.68);
insert into city (name, population) values ('Qinhong', 265.07);
insert into city (name, population) values ('Welisara', 920.53);
insert into city (name, population) values ('Zhangshi', 548.27);
insert into city (name, population) values ('Mancogeh', 383.09);
insert into city (name, population) values ('Dokshytsy', 158.61);
insert into city (name, population) values ('Sandwīp', 850.61);
insert into city (name, population) values ('Padre Burgos', 108.18);
insert into city (name, population) values ('Krzęcin', 699.33);
insert into city (name, population) values ('Rio Piracicaba', 870.74);
insert into city (name, population) values ('Ganhe', 872.59);
insert into city (name, population) values ('Ágios Týchon', 836.47);
insert into city (name, population) values ('Daya', 483.75);
insert into city (name, population) values ('Tabunok', 875.82);
insert into city (name, population) values ('Rumphi', 917.33);
insert into city (name, population) values ('Kujang', 772.97);
insert into city (name, population) values ('Piritiba', 360.0);
insert into city (name, population) values ('Debar', 698.32);
insert into city (name, population) values ('Jeffersonville', 542.96);
insert into city (name, population) values ('Brest', 485.82);
insert into city (name, population) values ('Jatiklampok', 963.31);
insert into city (name, population) values ('Wanmu', 502.85);
insert into city (name, population) values ('Mount Ayliff', 857.27);
insert into city (name, population) values ('Karpushikha', 895.52);
insert into city (name, population) values ('Rāmhormoz', 479.78);
insert into city (name, population) values ('Yixi', 532.36);
insert into city (name, population) values ('San Diego', 358.23);
insert into city (name, population) values ('Banikoara', 357.11);
insert into city (name, population) values ('San Antonio', 374.26);
insert into city (name, population) values ('Jinan', 436.97);
insert into city (name, population) values ('Tumbi', 458.5);
insert into city (name, population) values ('Tenri', 496.61);
insert into city (name, population) values ('Sandao', 452.39);
insert into city (name, population) values ('Söderköping', 707.54);
insert into city (name, population) values ('El Copey', 713.75);
insert into city (name, population) values ('Brckovljani', 861.42);
insert into city (name, population) values ('Baoxing', 713.6);
insert into city (name, population) values ('Mercedes', 960.12);
insert into city (name, population) values ('Tielou', 115.08);
insert into city (name, population) values ('Jandaia do Sul', 994.2);
insert into city (name, population) values ('Ampara', 260.56);
insert into city (name, population) values ('Hutang', 954.68);
insert into city (name, population) values ('Kurunegala', 589.87);
insert into city (name, population) values ('Fenjie', 406.33);
insert into city (name, population) values ('Zarichchya', 772.1);
insert into city (name, population) values ('White Rock', 908.59);
insert into city (name, population) values ('Sumberdadi', 826.37);
insert into city (name, population) values ('Fengyuan', 877.18);
insert into city (name, population) values ('Xianyan', 671.33);
insert into city (name, population) values ('Puerto Madryn', 825.26);
insert into city (name, population) values ('Wangfu', 847.73);
insert into city (name, population) values ('Ōita', 611.3);
insert into city (name, population) values ('Пласница', 57.41);
insert into city (name, population) values ('Arcangel', 550.98);
insert into city (name, population) values ('Castro Daire', 544.53);
insert into city (name, population) values ('Wonosobo', 582.21);
insert into city (name, population) values ('Shah Alam', 289.06);
insert into city (name, population) values ('Dŭstí', 369.11);
insert into city (name, population) values ('Hedong', 384.62);
insert into city (name, population) values ('Bilhó', 298.77);
insert into city (name, population) values ('Zelenodolsk', 909.31);
insert into city (name, population) values ('Bayambang', 560.65);
insert into city (name, population) values ('Dabancheng', 170.91);
insert into city (name, population) values ('San Jose', 744.84);
insert into city (name, population) values ('Hanyuan', 988.15);
insert into city (name, population) values ('Głogów Małopolski', 380.93);
insert into city (name, population) values ('Gýtheio', 579.53);
insert into city (name, population) values ('Linan', 297.13);
insert into city (name, population) values ('Pondokunyur', 678.92);
insert into city (name, population) values ('Sancti Spíritus', 958.23);
insert into city (name, population) values ('Oepula', 949.22);
insert into city (name, population) values ('Verrettes', 128.7);
insert into city (name, population) values ('London', 737.1);
insert into city (name, population) values ('Clamart', 913.06);
insert into city (name, population) values ('Vällingby', 260.48);
insert into city (name, population) values ('Caucaguita', 38.83);
insert into city (name, population) values ('Tantamayo', 460.22);
insert into city (name, population) values ('Khatsyezhyna', 650.81);
insert into city (name, population) values ('Mākū', 32.36);
insert into city (name, population) values ('Khānpur', 169.52);
insert into city (name, population) values ('Roudnice nad Labem', 623.01);
insert into city (name, population) values ('Novokhovrino', 802.74);
insert into city (name, population) values ('Iberia', 554.1);
insert into city (name, population) values ('Bingerville', 489.46);
insert into city (name, population) values ('Zhifang', 862.3);
insert into city (name, population) values ('Concordia', 795.38);
insert into city (name, population) values ('Magapit', 159.16);
insert into city (name, population) values ('Besançon', 215.03);
insert into city (name, population) values ('Betong', 186.95);
insert into city (name, population) values ('Lençóis Paulista', 571.15);
insert into city (name, population) values ('Addis Ababa', 524.82);
insert into city (name, population) values ('Stamford', 950.05);
insert into city (name, population) values ('Jocotán', 641.91);
insert into city (name, population) values ('Padangcermin', 733.33);
insert into city (name, population) values ('Shisandaogou', 237.98);
insert into city (name, population) values ('Cambas', 111.8);
insert into city (name, population) values ('Xinan', 358.33);
insert into city (name, population) values ('Xinzhu', 394.61);
insert into city (name, population) values ('Bertoua', 346.09);
insert into city (name, population) values ('Forninho', 392.44);
insert into city (name, population) values ('Andoany', 143.97);
insert into city (name, population) values ('Kema', 232.04);
insert into city (name, population) values ('Zagoryanskiy', 845.03);
insert into city (name, population) values ('Venado Tuerto', 175.72);
insert into city (name, population) values ('Thị Trấn Bắc Yên', 995.3);
insert into city (name, population) values ('Jingyang', 961.02);
insert into city (name, population) values ('Simuay', 978.19);
insert into city (name, population) values ('Lugui', 272.23);
insert into city (name, population) values ('Daleman', 579.36);
insert into city (name, population) values ('Planovskoye', 62.92);
insert into city (name, population) values ('Crespo', 920.22);
insert into city (name, population) values ('Siraway', 137.54);
insert into city (name, population) values ('Chuarrancho', 6.22);
insert into city (name, population) values ('Sedatiagung', 513.56);
insert into city (name, population) values ('Samara', 442.78);
insert into city (name, population) values ('Pasirmadang', 45.88);
insert into city (name, population) values ('Balogo', 804.3);
insert into city (name, population) values ('Taipingguan', 603.81);
insert into city (name, population) values ('Luojiang', 332.58);
insert into city (name, population) values ('Zhuge', 442.22);
insert into city (name, population) values ('Xingren', 127.86);
insert into city (name, population) values ('Milaor', 916.5);
insert into city (name, population) values ('El Asintal', 346.73);
insert into city (name, population) values ('Dongfu', 117.18);
insert into city (name, population) values ('Congonhas', 367.97);
insert into city (name, population) values ('Zhangyelu', 110.12);
insert into city (name, population) values ('Järfälla', 958.68);
insert into city (name, population) values ('Injīl', 883.63);
insert into city (name, population) values ('Bennäs', 298.07);
insert into city (name, population) values ('Fuzhiping', 855.34);
insert into city (name, population) values ('Kōriyama', 177.3);
insert into city (name, population) values ('Dagkar', 315.61);
insert into city (name, population) values ('Jiadingzhen', 926.04);
insert into city (name, population) values ('Richard-Toll', 384.99);
insert into city (name, population) values ('Adare', 201.15);
insert into city (name, population) values ('Libuganon', 337.1);
insert into city (name, population) values ('Pato-o', 387.44);
insert into city (name, population) values ('Cikaludan', 992.05);
insert into city (name, population) values ('Brańsk', 160.58);
insert into city (name, population) values ('Cabuyaro', 76.34);
insert into city (name, population) values ('Yizhang Chengguanzhen', 146.08);
insert into city (name, population) values ('Newton', 502.04);
insert into city (name, population) values ('Santa Fe', 632.09);
insert into city (name, population) values ('Zhuravka', 464.81);
insert into city (name, population) values ('Ndago', 734.65);
insert into city (name, population) values ('Yong’an', 968.44);
insert into city (name, population) values ('Ōtsuki', 926.15);
insert into city (name, population) values ('Nynäshamn', 449.6);
insert into city (name, population) values ('Cilangkap', 197.82);
insert into city (name, population) values ('Sakura', 72.53);
insert into city (name, population) values ('Tobelo', 512.89);
insert into city (name, population) values ('Thanh Ba', 402.72);
insert into city (name, population) values ('Allkaj', 530.77);
insert into city (name, population) values ('Shiziling', 793.28);
insert into city (name, population) values ('Korolëv Stan', 675.74);
insert into city (name, population) values ('Guxi', 863.19);
insert into city (name, population) values ('Barţa‘ah ash Sharqīyah', 300.3);
insert into city (name, population) values ('Sarankhola', 374.56);
insert into city (name, population) values ('Nanyang', 404.02);
insert into city (name, population) values ('Bukuru', 71.68);
insert into city (name, population) values ('Kalmar', 316.06);
insert into city (name, population) values ('Nanshi', 190.74);
insert into city (name, population) values ('Apucarana', 28.23);
insert into city (name, population) values ('Sobang', 989.89);
insert into city (name, population) values ('Sindangraja', 985.32);
insert into city (name, population) values ('Shentang', 951.42);
insert into city (name, population) values ('Pasiragung', 23.1);
insert into city (name, population) values ('Sumberpandan', 334.67);
insert into city (name, population) values ('Tianzhuang', 347.74);
insert into city (name, population) values ('Papilawe', 181.2);
insert into city (name, population) values ('Effium', 755.43);
insert into city (name, population) values ('Ishimbay', 698.38);
insert into city (name, population) values ('Judaydah', 595.2);
insert into city (name, population) values ('Masuguru', 906.4);
insert into city (name, population) values ('Konakridee', 455.69);
insert into city (name, population) values ('Gubin', 505.64);
insert into city (name, population) values ('Nevyts’ke', 208.16);
insert into city (name, population) values ('Bato', 284.07);
insert into city (name, population) values ('Araguari', 528.58);
insert into city (name, population) values ('Kupchino', 232.93);
insert into city (name, population) values ('Haveluloto', 623.97);
insert into city (name, population) values ('Kidatu', 962.25);
insert into city (name, population) values ('Gemo', 201.12);
insert into city (name, population) values ('Fussa', 757.77);
insert into city (name, population) values ('Dharān Bāzār', 380.97);
insert into city (name, population) values ('Guatraché', 215.91);
insert into city (name, population) values ('Enskede', 290.39);
insert into city (name, population) values ('Kachar', 813.25);
insert into city (name, population) values ('Karangmulyo', 377.2);
insert into city (name, population) values ('Staryy Oskol', 389.76);
insert into city (name, population) values ('Ijūin', 938.0);
insert into city (name, population) values ('Tapado', 102.97);
insert into city (name, population) values ('Bohutín', 195.76);
insert into city (name, population) values ('Cairani', 10.88);
insert into city (name, population) values ('Villefontaine', 947.14);
insert into city (name, population) values ('Iwye', 779.6);
insert into city (name, population) values ('Carmen', 836.42);
insert into city (name, population) values ('Yongfa', 795.16);
insert into city (name, population) values ('Limoges', 166.34);
insert into city (name, population) values ('Latacunga', 49.67);
insert into city (name, population) values ('Oklahoma City', 321.72);
insert into city (name, population) values ('Lhabupu', 758.02);
insert into city (name, population) values ('Tohautu', 724.6);
insert into city (name, population) values ('Zhichu', 261.77);
insert into city (name, population) values ('Masaya', 850.31);
insert into city (name, population) values ('Władysławowo', 389.14);
insert into city (name, population) values ('Valka', 64.14);
insert into city (name, population) values ('Huangnaihai', 766.78);
insert into city (name, population) values ('Serrinha', 746.32);
insert into city (name, population) values ('Columbeira', 365.77);
insert into city (name, population) values ('Dutsin Ma', 717.87);
insert into city (name, population) values ('Xiaodukou', 373.89);
insert into city (name, population) values ('Boulogne-sur-Mer', 648.93);
insert into city (name, population) values ('Semey', 784.74);
insert into city (name, population) values ('Vårby', 770.33);
insert into city (name, population) values ('Atins', 524.31);
insert into city (name, population) values ('Skoki', 226.27);
insert into city (name, population) values ('São Gonçalo do Sapucaí', 540.31);
insert into city (name, population) values ('Brooklyn', 102.91);
insert into city (name, population) values ('Shilu', 666.88);
insert into city (name, population) values ('La Soledad', 300.55);
insert into city (name, population) values ('Witihama', 49.65);
insert into city (name, population) values ('Araucária', 207.09);
insert into city (name, population) values ('Charleston', 789.13);
insert into city (name, population) values ('Villa Dolores', 748.54);
insert into city (name, population) values ('Beicang', 914.78);
insert into city (name, population) values ('Wucun', 280.47);
insert into city (name, population) values ('Lalupon', 324.3);
insert into city (name, population) values ('Tuanjie', 129.98);
insert into city (name, population) values ('Sade', 90.5);
insert into city (name, population) values ('Linköping', 706.29);
insert into city (name, population) values ('Tantamayo', 712.6);
insert into city (name, population) values ('Tajur', 154.08);
insert into city (name, population) values ('Chemerivtsi', 660.28);
insert into city (name, population) values ('Plereyan', 851.51);
insert into city (name, population) values ('Doghs', 268.06);
insert into city (name, population) values ('Watulimo', 2.78);
insert into city (name, population) values ('Burträsk', 142.42);
insert into city (name, population) values ('Huiwan', 3.48);
insert into city (name, population) values ('Rochester', 204.43);
insert into city (name, population) values ('Huangjiabu', 278.06);
insert into city (name, population) values ('Colonia Elía', 617.17);
insert into city (name, population) values ('Ratilangi', 459.01);
insert into city (name, population) values ('Kurów', 583.52);
insert into city (name, population) values ('Parengan', 648.54);
insert into city (name, population) values ('Wenchang', 473.5);
insert into city (name, population) values ('Moreno', 753.45);
insert into city (name, population) values ('Manicahan', 692.39);
insert into city (name, population) values ('Vegreville', 347.02);
insert into city (name, population) values ('Voi', 370.73);
insert into city (name, population) values ('Bangekdewa', 620.2);
insert into city (name, population) values ('Simpang', 247.35);
insert into city (name, population) values ('Thymianá', 805.05);
insert into city (name, population) values ('Xinhua', 112.33);
insert into city (name, population) values ('Vårby', 616.36);
insert into city (name, population) values ('Motala', 767.9);
insert into city (name, population) values ('Chaloem Phra Kiat', 633.38);
insert into city (name, population) values ('Babana', 37.16);
insert into city (name, population) values ('Dalheim', 544.53);
insert into city (name, population) values ('Jinshi', 225.54);
insert into city (name, population) values ('Paihia', 690.87);
insert into city (name, population) values ('Cogon', 832.34);
insert into city (name, population) values ('Katagum', 941.57);
insert into city (name, population) values ('Gisiliba', 244.42);
insert into city (name, population) values ('Montijo', 268.17);
insert into city (name, population) values ('Lantian', 273.38);
insert into city (name, population) values ('Gushi', 375.92);
insert into city (name, population) values ('Pórto Chéli', 294.11);
insert into city (name, population) values ('Esmoriz', 525.82);
insert into city (name, population) values ('Luofang', 782.16);
insert into city (name, population) values ('Marco', 325.95);
insert into city (name, population) values ('Tibakisa', 271.67);
insert into city (name, population) values ('Bandung', 900.99);
insert into city (name, population) values ('Lambton Shores', 887.53);
insert into city (name, population) values ('Gaogu', 253.33);
insert into city (name, population) values ('Östersund', 90.98);
insert into city (name, population) values ('Zaplavnoye', 286.88);
insert into city (name, population) values ('Kusak', 252.83);
insert into city (name, population) values ('Zhuting', 466.26);
insert into city (name, population) values ('Spassk-Dal’niy', 71.44);
insert into city (name, population) values ('Yanglin', 94.52);
insert into city (name, population) values ('Larvik', 246.59);
insert into city (name, population) values ('Caetité', 67.86);
insert into city (name, population) values ('Gharavŭtí', 107.77);
insert into city (name, population) values ('Dajing', 233.22);
insert into city (name, population) values ('Amiens', 119.23);
insert into city (name, population) values ('Paris La Défense', 950.35);
insert into city (name, population) values ('Jiabeiyan', 271.0);
insert into city (name, population) values ('Mo I Rana', 758.65);
insert into city (name, population) values ('Shuiyang', 256.82);
insert into city (name, population) values ('Pandean', 243.77);
insert into city (name, population) values ('Zhouling', 21.67);
insert into city (name, population) values ('Moreno', 80.08);
insert into city (name, population) values ('San Simon', 850.17);
insert into city (name, population) values ('Xiangdian', 672.4);
insert into city (name, population) values ('Hexi', 142.82);
insert into city (name, population) values ('Beijie', 801.95);
insert into city (name, population) values ('Cawayan', 19.49);
insert into city (name, population) values ('Fanzhuang', 974.51);
insert into city (name, population) values ('Strömsnäsbruk', 143.38);
insert into city (name, population) values ('Rungis', 162.8);
insert into city (name, population) values ('Sophia Antipolis', 303.45);
insert into city (name, population) values ('Brezovica', 922.08);
insert into city (name, population) values ('Cernache do Bonjardim', 995.48);
insert into city (name, population) values ('Brodósqui', 789.94);
insert into city (name, population) values ('Babao', 796.23);
insert into city (name, population) values ('Cikalaces', 592.98);
insert into city (name, population) values ('Namp’o', 38.23);
insert into city (name, population) values ('Neyvo-Rudyanka', 838.76);
insert into city (name, population) values ('Kisii', 213.73);
insert into city (name, population) values ('Opařany', 63.68);
insert into city (name, population) values ('Bahía de Caráquez', 707.41);
insert into city (name, population) values ('Hongxingqiao', 746.31);
insert into city (name, population) values ('Numazu', 700.22);
insert into city (name, population) values ('Karadaglije', 998.27);
insert into city (name, population) values ('Lingqian', 223.05);
insert into city (name, population) values ('Shunde', 452.86);
insert into city (name, population) values ('San Francisco', 61.96);
insert into city (name, population) values ('Krasnaya Polyana', 222.61);
insert into city (name, population) values ('Mora', 909.32);
insert into city (name, population) values ('Ciawitali', 606.42);
insert into city (name, population) values ('Blarney', 408.25);
insert into city (name, population) values ('Jingkou', 116.6);
insert into city (name, population) values ('Berehomet', 167.98);
insert into city (name, population) values ('Tomakomai', 348.61);
insert into city (name, population) values ('Stockholm', 565.19);
insert into city (name, population) values ('Hongtian', 71.32);
insert into city (name, population) values ('Quinta dos Frades', 699.67);
insert into city (name, population) values ('Agdzhabedy', 212.98);
insert into city (name, population) values ('May Pen', 369.06);
insert into city (name, population) values ('Pokrovskoye', 117.77);
insert into city (name, population) values ('Chone', 110.74);
insert into city (name, population) values ('Hulín', 992.8);
insert into city (name, population) values ('Al Hadā', 676.83);
insert into city (name, population) values ('Kashira', 337.89);
insert into city (name, population) values ('Charleroi', 869.37);
insert into city (name, population) values ('Ciechanów', 804.56);
insert into city (name, population) values ('Semiluki', 312.91);
insert into city (name, population) values ('Bárrio', 580.22);
insert into city (name, population) values ('San Julian', 97.71);
insert into city (name, population) values ('Yong’an', 1.36);
insert into city (name, population) values ('Hannover', 761.3);
insert into city (name, population) values ('Laifang', 974.63);
insert into city (name, population) values ('Novais', 785.62);
insert into city (name, population) values ('Mira', 753.5);
insert into city (name, population) values ('Ostroróg', 137.87);
insert into city (name, population) values ('Jiancheng', 835.19);
insert into city (name, population) values ('Yélimané', 12.3);
insert into city (name, population) values ('Saint-Quentin-en-Yvelines', 687.66);
insert into city (name, population) values ('Kolbudy', 797.15);
insert into city (name, population) values ('Gagarawa', 876.47);
insert into city (name, population) values ('Gijon', 382.46);
insert into city (name, population) values ('Yuyue', 102.61);
insert into city (name, population) values ('Göteborg', 692.41);
insert into city (name, population) values ('Petushki', 722.56);
insert into city (name, population) values ('Santa María de Jesús', 70.93);
insert into city (name, population) values ('Wolonio', 734.22);
insert into city (name, population) values ('La Soledad', 40.09);
insert into city (name, population) values ('Sułkowice', 996.71);
insert into city (name, population) values ('Chisong', 649.28);
insert into city (name, population) values ('Valdosta', 444.82);
insert into city (name, population) values ('Andrijevica', 165.52);
insert into city (name, population) values ('Suḩayl Shibām', 555.92);
insert into city (name, population) values ('Salt Lake City', 946.85);
insert into city (name, population) values ('Castellon De La Plana/Castello De La Pla', 896.02);
insert into city (name, population) values ('Pisang', 695.35);
insert into city (name, population) values ('Ngedhusuba', 990.7);
insert into city (name, population) values ('Dongtundu', 428.51);
insert into city (name, population) values ('Kemil', 115.8);
insert into city (name, population) values ('Gualeguay', 525.57);
insert into city (name, population) values ('Koungheul', 139.3);
insert into city (name, population) values ('Primorsk', 278.31);
insert into city (name, population) values ('Gierłoż', 249.94);
insert into city (name, population) values ('Bocos', 1.11);
insert into city (name, population) values ('Longmen', 587.65);
insert into city (name, population) values ('Abang', 156.22);
insert into city (name, population) values ('Dimayon', 693.81);
insert into city (name, population) values ('Pulosari', 452.49);
insert into city (name, population) values ('Bīrganj', 403.18);
insert into city (name, population) values ('Longping', 185.09);
insert into city (name, population) values ('Caracal', 892.84);
insert into city (name, population) values ('Nizhnyaya Tura', 687.48);
insert into city (name, population) values ('Changxi', 657.7);
insert into city (name, population) values ('Lyublino', 270.48);
insert into city (name, population) values ('Huamali', 603.55);
insert into city (name, population) values ('Greensboro', 988.72);
insert into city (name, population) values ('Ust’ye', 678.33);
insert into city (name, population) values ('Batanghari', 597.25);
insert into city (name, population) values ('Molochnoye', 349.86);
insert into city (name, population) values ('Paseyan', 675.05);
insert into city (name, population) values ('Puzi', 717.26);
insert into city (name, population) values ('El Capulin', 800.93);
insert into city (name, population) values ('Zudun', 658.55);
insert into city (name, population) values ('Ozubulu', 270.37);
insert into city (name, population) values ('Giporlos', 474.14);
insert into city (name, population) values ('Salvacion', 29.42);
insert into city (name, population) values ('Panji', 73.76);
insert into city (name, population) values ('Tiouli', 352.74);
insert into city (name, population) values ('Waco', 293.25);
insert into city (name, population) values ('Kuçovë', 109.03);
insert into city (name, population) values ('Whakatane', 157.17);
insert into city (name, population) values ('Chenji', 554.58);
insert into city (name, population) values ('Kedungbacin', 380.88);
insert into city (name, population) values ('Sarandi', 697.54);
insert into city (name, population) values ('Gradizhsk', 149.46);
insert into city (name, population) values ('Hollola', 87.63);
insert into city (name, population) values ('Köneürgench', 23.84);
insert into city (name, population) values ('Guernica', 936.43);
insert into city (name, population) values ('Dzüyl', 624.04);
insert into city (name, population) values ('Lagunillas', 536.21);
insert into city (name, population) values ('Al Ḩarajah', 581.97);
insert into city (name, population) values ('Manisi', 253.26);
insert into city (name, population) values ('Sukaraharja', 573.86);
insert into city (name, population) values ('Nuasepu', 234.93);
insert into city (name, population) values ('Aduo', 733.51);
insert into city (name, population) values ('Mabua', 226.74);
insert into city (name, population) values ('Libertad', 885.32);
insert into city (name, population) values ('Pondaguitan', 8.59);
insert into city (name, population) values ('Dashahe', 279.47);
insert into city (name, population) values ('Yong’an', 805.86);
insert into city (name, population) values ('Jīsh', 222.86);
insert into city (name, population) values ('Tyrnyauz', 911.77);
insert into city (name, population) values ('Kizel', 312.83);
insert into city (name, population) values ('Koropí', 815.87);
insert into city (name, population) values ('Kuala Terengganu', 188.69);
insert into city (name, population) values ('Sara Kunda', 235.91);
insert into city (name, population) values ('Velykyy Klyuchiv', 65.98);
insert into city (name, population) values ('Media Luna', 69.61);
insert into city (name, population) values ('Jieshan', 473.38);
insert into city (name, population) values ('Okrika', 561.09);
insert into city (name, population) values ('Krajan Dua Patempuran', 187.78);
insert into city (name, population) values ('Guanqian', 878.6);
insert into city (name, population) values ('Teluk Pinang', 84.26);
insert into city (name, population) values ('Sangallaya', 953.79);
insert into city (name, population) values ('Bilicenii Vechi', 965.25);
insert into city (name, population) values ('Bohdalov', 646.65);
insert into city (name, population) values ('Dongfu', 471.8);
insert into city (name, population) values ('Hīrna', 942.87);
insert into city (name, population) values ('San Jose', 160.59);
insert into city (name, population) values ('General Conesa', 501.06);
insert into city (name, population) values ('Cagayan', 561.26);
insert into city (name, population) values ('Bacong', 105.86);
insert into city (name, population) values ('Cambebba', 329.8);
insert into city (name, population) values ('Liangdang Chengguanzhen', 231.18);
insert into city (name, population) values ('Tegallega', 523.43);
insert into city (name, population) values ('Fojo', 513.78);
insert into city (name, population) values ('Courelas Bravas', 966.51);
insert into city (name, population) values ('Xiangjia', 585.88);
insert into city (name, population) values ('Seara', 418.27);
insert into city (name, population) values ('Kista', 714.7);
insert into city (name, population) values ('Trinity Ville', 688.17);
insert into city (name, population) values ('Wisła', 668.85);
insert into city (name, population) values ('Pilníkov', 201.76);
insert into city (name, population) values ('Jinchang', 532.28);
insert into city (name, population) values ('Idfu', 171.9);
insert into city (name, population) values ('Kökar', 959.98);
insert into city (name, population) values ('Bartolomé Masó', 486.39);
insert into city (name, population) values ('Volovo', 837.53);
insert into city (name, population) values ('Castainço', 66.28);
insert into city (name, population) values ('Vendychany', 999.71);
insert into city (name, population) values ('Colorado', 90.25);
insert into city (name, population) values ('Sławatycze', 833.36);
insert into city (name, population) values ('Xam Nua', 746.73);
insert into city (name, population) values ('Qarchī Gak', 334.57);
insert into city (name, population) values ('Pagsanahan Norte', 866.53);
insert into city (name, population) values ('Mitzpe Ramon', 317.79);
insert into city (name, population) values ('Malianzhuang', 292.42);
insert into city (name, population) values ('Ōtsuki', 390.89);
insert into city (name, population) values ('Gaolong', 413.96);
insert into city (name, population) values ('Yangji', 801.35);
insert into city (name, population) values ('Leme', 245.05);
insert into city (name, population) values ('Taixi', 57.92);
insert into city (name, population) values ('Kasukabe', 55.51);
insert into city (name, population) values ('Penengahan', 324.32);
insert into city (name, population) values ('Stuttgart Stuttgart-Mitte', 182.73);
insert into city (name, population) values ('Conchopata', 885.54);
insert into city (name, population) values ('Pajoreja', 228.17);
insert into city (name, population) values ('Dawang', 930.16);
insert into city (name, population) values ('Mabusag', 966.09);
insert into city (name, population) values ('Itéa', 392.23);
insert into city (name, population) values ('Xiaozhoushan', 33.51);
insert into city (name, population) values ('Starokorsunskaya', 742.72);
insert into city (name, population) values ('Järvakandi', 152.87);
insert into city (name, population) values ('Östersund', 50.88);
insert into city (name, population) values ('Daqin Tal', 622.64);
insert into city (name, population) values ('Huangtian', 339.21);
insert into city (name, population) values ('Idrinskoye', 991.43);
insert into city (name, population) values ('Dzüünbulag', 842.05);
insert into city (name, population) values ('Fatumnasi', 139.97);
insert into city (name, population) values ('Oxford', 100.99);
insert into city (name, population) values ('Tabiauan', 986.54);
insert into city (name, population) values ('Cascais', 111.86);
insert into city (name, population) values ('Maceda', 477.02);
insert into city (name, population) values ('Tiedonglu', 454.53);
insert into city (name, population) values ('Tangyu', 400.29);
insert into city (name, population) values ('Lubień Kujawski', 781.48);
insert into city (name, population) values ('Valvedditturai', 435.73);
insert into city (name, population) values ('Burgersfort', 971.8);
insert into city (name, population) values ('Gataivai', 117.96);
insert into city (name, population) values ('Jiaozuo', 788.79);
insert into city (name, population) values ('Verdun', 335.66);
insert into city (name, population) values ('Hushan', 62.23);
insert into city (name, population) values ('Meilin', 1.44);
insert into city (name, population) values ('Kawangu Satu', 26.46);
insert into city (name, population) values ('Pszczew', 376.67);
insert into city (name, population) values ('Wanagiri', 913.93);
insert into city (name, population) values ('Paoua', 215.9);
insert into city (name, population) values ('Nam Phong', 493.03);
insert into city (name, population) values ('Visby', 66.76);
insert into city (name, population) values ('Arevik', 838.65);
insert into city (name, population) values ('Karpushikha', 952.72);
insert into city (name, population) values ('Dazu', 20.14);
insert into city (name, population) values ('Santa Maria', 414.77);
insert into city (name, population) values ('Dapchi', 668.57);
insert into city (name, population) values ('Huangtukuang', 650.32);
insert into city (name, population) values ('Drachten', 849.51);
insert into city (name, population) values ('Sernancelhe', 531.96);
insert into city (name, population) values ('Kristiansand S', 337.06);
insert into city (name, population) values ('Arnaía', 224.5);
insert into city (name, population) values ('Irvine', 97.73);
insert into city (name, population) values ('Tamot', 659.58);
insert into city (name, population) values ('Paris 01', 53.94);
insert into city (name, population) values ('Yedogon', 301.25);
insert into city (name, population) values ('Skomlin', 22.95);
insert into city (name, population) values ('Agbani', 45.86);
insert into city (name, population) values ('Tyrawa Wołoska', 962.76);
insert into city (name, population) values ('Khosta', 178.89);
insert into city (name, population) values ('Chaloem Phra Kiat', 945.26);
insert into city (name, population) values ('Galūgāh', 460.82);
insert into city (name, population) values ('Bīrganj', 365.35);
insert into city (name, population) values ('Tangzha', 347.93);
insert into city (name, population) values ('Campana', 477.14);
insert into city (name, population) values ('Jujur', 939.95);
insert into city (name, population) values ('Xiaruyue', 252.01);
insert into city (name, population) values ('Feodosiya', 881.93);
insert into city (name, population) values ('Syców', 645.33);
insert into city (name, population) values ('Seoam', 537.97);
insert into city (name, population) values ('Sobral', 490.31);
insert into city (name, population) values ('Puerto Cabezas', 206.11);
insert into city (name, population) values ('Chejiazhuang', 335.04);
insert into city (name, population) values ('Wangjing', 685.0);
insert into city (name, population) values ('Turochak', 461.62);
insert into city (name, population) values ('Varaždin', 282.61);
insert into city (name, population) values ('Kanigorokrajan', 28.87);
insert into city (name, population) values ('Gaohong', 644.31);
insert into city (name, population) values ('Partesh', 145.0);
insert into city (name, population) values ('Chayuan', 229.13);
insert into city (name, population) values ('Widorokandang', 834.84);
insert into city (name, population) values ('Ulan Us', 519.4);
insert into city (name, population) values ('Laironja', 897.66);
insert into city (name, population) values ('Yuracyacu', 517.54);
insert into city (name, population) values ('Kryry', 728.61);
insert into city (name, population) values ('Mabuttal East', 12.39);
insert into city (name, population) values ('Camangcamang', 52.52);
insert into city (name, population) values ('Yong’an', 386.53);
insert into city (name, population) values ('Akune', 83.54);
insert into city (name, population) values ('Kalebun', 493.16);
insert into city (name, population) values ('Leijiadian', 810.79);
insert into city (name, population) values ('Londrina', 537.85);
insert into city (name, population) values ('Tongguan', 737.71);
insert into city (name, population) values ('Behbahān', 429.32);
insert into city (name, population) values ('Mosteirô', 574.52);
insert into city (name, population) values ('Bhisho', 282.49);
insert into city (name, population) values ('Mairana', 677.55);
insert into city (name, population) values ('Šenov', 813.23);
insert into city (name, population) values ('Shaheying', 196.36);
insert into city (name, population) values ('Paka', 790.11);
insert into city (name, population) values ('Karangagung Timur', 657.28);
insert into city (name, population) values ('Nowe Skalmierzyce', 239.51);
insert into city (name, population) values ('Makale', 21.9);
insert into city (name, population) values ('Wróblew', 744.12);
insert into city (name, population) values ('Zhoupu', 701.63);
insert into city (name, population) values ('Guatimozín', 127.56);
insert into city (name, population) values ('Hezhi', 839.88);
insert into city (name, population) values ('Řehlovice', 655.96);
insert into city (name, population) values ('Limoeiro do Norte', 301.67);
insert into city (name, population) values ('Pátmos', 824.93);
insert into city (name, population) values ('Stockholm', 691.15);
insert into city (name, population) values ('Tékane', 23.43);
insert into city (name, population) values ('Gornje Moštre', 311.52);
insert into city (name, population) values ('Makui', 759.02);
insert into city (name, population) values ('Kelo', 45.21);
insert into city (name, population) values ('Tarkastad', 301.86);
insert into city (name, population) values ('Medveđa', 357.59);
insert into city (name, population) values ('Monjarás', 88.52);
insert into city (name, population) values ('Cilimus Kulon', 360.39);
insert into city (name, population) values ('Muara Siberut', 490.57);
insert into city (name, population) values ('São Mamede de Infesta', 31.68);
insert into city (name, population) values ('Longping', 553.98);
insert into city (name, population) values ('Gobernador Ingeniero Valentín Virasoro', 656.95);
insert into city (name, population) values ('Hal’shany', 203.74);
insert into city (name, population) values ('Al ‘Ulá', 952.64);
insert into city (name, population) values ('Neqāb', 915.99);
insert into city (name, population) values ('Kambatatamakawu', 123.61);
insert into city (name, population) values ('Vlachovo Březí', 315.04);
insert into city (name, population) values ('Machida', 53.67);
insert into city (name, population) values ('Shangshaleng', 318.61);
insert into city (name, population) values ('Heping', 737.67);
insert into city (name, population) values ('Smolenka', 344.03);
insert into city (name, population) values ('Manukaka', 975.14);
insert into city (name, population) values ('Citundun', 938.6);
insert into city (name, population) values ('Haoba', 174.41);
insert into city (name, population) values ('Srunikrajan', 896.2);
insert into city (name, population) values ('Diveyevo', 818.65);
insert into city (name, population) values ('Bassila', 67.85);
insert into city (name, population) values ('Perepravnaya', 83.74);
insert into city (name, population) values ('Ludwin', 747.37);
insert into city (name, population) values ('Mae Ramat', 986.38);
insert into city (name, population) values ('Novozavidovskiy', 32.58);
insert into city (name, population) values ('Tavira', 941.65);
insert into city (name, population) values ('Tegina', 893.91);
insert into city (name, population) values ('Pasatan', 896.46);
insert into city (name, population) values ('Hidalgo', 514.86);
insert into city (name, population) values ('Gaspar', 626.85);
insert into city (name, population) values ('Kalian', 609.14);
insert into city (name, population) values ('Araci', 832.81);
insert into city (name, population) values ('Xiangshui', 424.11);
insert into city (name, population) values ('Pinhal de Frades', 869.89);
insert into city (name, population) values ('Kaolack', 443.98);
insert into city (name, population) values ('Kekeran', 770.75);
insert into city (name, population) values ('Huangshan', 756.38);
insert into city (name, population) values ('Yukuhashi', 768.01);
insert into city (name, population) values ('Salt Lake City', 300.83);
insert into city (name, population) values ('Picoto', 653.08);
insert into city (name, population) values ('Ozimek', 325.81);
insert into city (name, population) values ('Lusk', 911.89);
insert into city (name, population) values ('Luoqi', 679.04);
insert into city (name, population) values ('Czarków', 488.01);
insert into city (name, population) values ('Wuli', 691.77);
insert into city (name, population) values ('Ntonggu', 461.56);
insert into city (name, population) values ('Baylo', 431.39);
insert into city (name, population) values ('Agustín Codazzi', 671.83);
insert into city (name, population) values ('Hồ Xá', 876.03);
insert into city (name, population) values ('Cheb', 158.05);
insert into city (name, population) values ('Kourou', 46.99);
insert into city (name, population) values ('Yaransk', 648.13);
insert into city (name, population) values ('Coolock', 524.25);
insert into city (name, population) values ('Túquerres', 134.91);
insert into city (name, population) values ('Kletek', 348.66);
insert into city (name, population) values ('Kauhava', 395.97);
insert into city (name, population) values ('Sainte-Marthe-sur-le-Lac', 753.35);
insert into city (name, population) values ('Kamenný Přívoz', 473.75);
insert into city (name, population) values ('Geputan', 49.49);
insert into city (name, population) values ('Itaguaí', 108.08);
insert into city (name, population) values ('Ariquemes', 946.34);
insert into city (name, population) values ('Znamenskoye', 873.76);
insert into city (name, population) values ('Södra Sandby', 148.19);
insert into city (name, population) values ('Hrabyně', 736.63);
insert into city (name, population) values ('Nyköping', 864.82);
insert into city (name, population) values ('Banjar Taro Kelod', 691.6);
insert into city (name, population) values ('Dongxin', 413.39);
insert into city (name, population) values ('Jianguang', 785.39);
insert into city (name, population) values ('Tô Hạp', 302.21);
insert into city (name, population) values ('Xiamujiao', 848.66);
insert into city (name, population) values ('Abdurahmoni Jomí', 988.03);
insert into city (name, population) values ('Jinshan', 925.26);
insert into city (name, population) values ('Marulanda', 613.86);
insert into city (name, population) values ('Karangsari', 603.95);
insert into city (name, population) values ('Cikuning', 243.18);
insert into city (name, population) values ('Laḩij', 904.41);
insert into city (name, population) values ('Jieshipu', 441.0);
insert into city (name, population) values ('Ertai', 375.72);
insert into city (name, population) values ('Dimovo', 779.21);
insert into city (name, population) values ('Medovene', 262.01);
insert into city (name, population) values ('Rožmitál pod Třemšínem', 500.39);
insert into city (name, population) values ('Debar', 410.33);
insert into city (name, population) values ('San Pedro Pinula', 565.95);
insert into city (name, population) values ('Puerto Cabezas', 137.77);
insert into city (name, population) values ('Khromtau', 146.36);
insert into city (name, population) values ('Palma De Mallorca', 296.89);
insert into city (name, population) values ('Lidingö', 583.56);
insert into city (name, population) values ('Pasanggrahan', 502.55);
insert into city (name, population) values ('Salon-de-Provence', 84.34);
insert into city (name, population) values ('Tánh Linh', 254.88);
insert into city (name, population) values ('Chiryū', 28.74);
insert into city (name, population) values ('Rogóźno', 108.65);
insert into city (name, population) values ('Kawaguchi', 553.43);
insert into city (name, population) values ('Gongchenqiao', 366.43);
insert into city (name, population) values ('Godong', 881.78);
insert into city (name, population) values ('Pueblo Nuevo', 169.72);
insert into city (name, population) values ('Ząbkowice Śląskie', 47.37);
insert into city (name, population) values ('Chợ Mới', 614.0);
insert into city (name, population) values ('Afareaitu', 647.72);
insert into city (name, population) values ('Kwangmyŏng', 608.6);
insert into city (name, population) values ('Gunungpeundeuy', 803.78);
insert into city (name, population) values ('Futaleufú', 663.34);
insert into city (name, population) values ('Brétigny-sur-Orge', 746.0);
insert into city (name, population) values ('Cruces', 172.35);
insert into city (name, population) values ('Qingshui', 936.17);
insert into city (name, population) values ('Ponce', 521.07);
insert into city (name, population) values ('Paris 20', 419.68);
insert into city (name, population) values ('Haveliān', 813.91);
insert into city (name, population) values ('Jiqu', 95.38);
insert into city (name, population) values ('Courtaboeuf', 871.36);
insert into city (name, population) values ('Yanling', 313.42);
insert into city (name, population) values ('Huohua', 27.8);
insert into city (name, population) values ('Rembes', 795.43);
insert into city (name, population) values ('Odzi', 966.79);
insert into city (name, population) values ('Basud', 178.19);
insert into city (name, population) values ('Tampocon', 830.35);
insert into city (name, population) values ('Ikata-chō', 879.39);
insert into city (name, population) values ('Pachīr wa Āgām', 682.47);
insert into city (name, population) values ('Motegi', 650.25);
insert into city (name, population) values ('Phu Kradueng', 780.56);
insert into city (name, population) values ('Napu', 347.38);
insert into city (name, population) values ('Hroznětín', 332.07);
insert into city (name, population) values ('Youxi', 994.24);
insert into city (name, population) values ('Michurinskoye', 628.3);
insert into city (name, population) values ('Tsimlyansk', 152.34);
insert into city (name, population) values ('Horodyshche', 82.43);
insert into city (name, population) values ('La Paz', 224.19);
insert into city (name, population) values ('Farinheiras', 791.16);
insert into city (name, population) values ('Łomża', 110.93);
insert into city (name, population) values ('Oinoússes', 171.48);
insert into city (name, population) values ('Avaré', 907.9);
insert into city (name, population) values ('Tengger', 19.64);
insert into city (name, population) values ('Petrodvorets', 602.94);
insert into city (name, population) values ('Sukamaju', 453.67);
insert into city (name, population) values ('Erími', 423.0);
insert into city (name, population) values ('Kudamatsu', 860.13);
insert into city (name, population) values ('Paingar', 454.72);
insert into city (name, population) values ('Blimbing', 643.18);
insert into city (name, population) values ('Cottbus', 615.98);
insert into city (name, population) values ('Guay', 797.24);
insert into city (name, population) values ('Jelbuk', 947.89);
insert into city (name, population) values ('Minas de Oro', 10.06);
insert into city (name, population) values ('Lavradio', 383.32);
insert into city (name, population) values ('Mossendjo', 362.43);
insert into city (name, population) values ('Tha Yang', 686.93);
insert into city (name, population) values ('Muang Sam Sip', 414.43);
insert into city (name, population) values ('Hodkovice nad Mohelkou', 377.79);
insert into city (name, population) values ('Zongzhai', 556.17);
insert into city (name, population) values ('Puncaksari', 247.46);
insert into city (name, population) values ('Pasembon', 228.94);
insert into city (name, population) values ('Anwen', 953.18);
insert into city (name, population) values ('Sollefteå', 267.82);
insert into city (name, population) values ('Ebaye', 73.03);
insert into city (name, population) values ('El Paso', 156.72);
insert into city (name, population) values ('Karangdalam', 616.36);
insert into city (name, population) values ('Huayang', 686.51);
insert into city (name, population) values ('Arendal', 674.61);
insert into city (name, population) values ('Świlcza', 713.87);
insert into city (name, population) values ('Velyka Pysarivka', 816.2);
insert into city (name, population) values ('Höganäs', 197.07);
insert into city (name, population) values ('Kurortnyy', 741.47);
insert into city (name, population) values ('Nonghe', 719.37);
insert into city (name, population) values ('Betulia', 115.61);
insert into city (name, population) values ('El Sauce', 694.62);
insert into city (name, population) values ('Tongyuanpu', 861.91);
insert into city (name, population) values ('Lazaro Cardenas', 224.7);
insert into city (name, population) values ('Hongqi', 282.55);
insert into city (name, population) values ('Lindavista', 662.78);
insert into city (name, population) values ('San Pedro Jocopilas', 903.34);
insert into city (name, population) values ('Neni', 784.45);
insert into city (name, population) values ('Ponte da Pedra', 708.73);
insert into city (name, population) values ('Padre Las Casas', 11.97);
insert into city (name, population) values ('Xiejia', 969.84);
insert into city (name, population) values ('Fenjie', 904.67);
insert into city (name, population) values ('Alcorriol', 590.28);
insert into city (name, population) values ('La Puerta de San José', 74.36);
insert into city (name, population) values ('Ostrów Mazowiecka', 314.88);
insert into city (name, population) values ('Non Sung', 166.61);
insert into city (name, population) values ('Jiyizhuang', 469.74);
insert into city (name, population) values ('Pustomyty', 468.49);
insert into city (name, population) values ('Los Rastrojos', 346.61);
insert into city (name, population) values ('Międzyzdroje', 660.39);
insert into city (name, population) values ('Đống Đa', 946.63);
insert into city (name, population) values ('Lutian', 296.27);
insert into city (name, population) values ('Baton Rouge', 532.56);
insert into city (name, population) values ('Labuan', 858.31);
insert into city (name, population) values ('Пласница', 388.58);
insert into city (name, population) values ('Tanggulangin', 762.58);
insert into city (name, population) values ('Santiago Atitlán', 948.91);
insert into city (name, population) values ('Umbuldamar', 991.24);
insert into city (name, population) values ('Hāgere Hiywet', 667.68);
insert into city (name, population) values ('Paris 20', 194.83);
insert into city (name, population) values ('Järfälla', 218.46);
insert into city (name, population) values ('København', 158.5);
insert into city (name, population) values ('Taoyao', 622.75);
insert into city (name, population) values ('Askim', 676.64);
insert into city (name, population) values ('Yong’an', 139.46);
insert into city (name, population) values ('Huelkail', 765.23);
insert into city (name, population) values ('Dar Chabanne', 437.03);
insert into city (name, population) values ('Chester', 338.58);
insert into city (name, population) values ('Cipasung', 608.73);
insert into city (name, population) values ('Oranjestad', 899.52);
insert into city (name, population) values ('Liuzu', 518.25);
insert into city (name, population) values ('Gegernoong', 37.36);
insert into city (name, population) values ('Bela Vista', 632.69);
insert into city (name, population) values ('Capitán Sarmiento', 465.59);
insert into city (name, population) values ('Wukou', 66.67);
insert into city (name, population) values ('Helsingborg', 898.98);
insert into city (name, population) values ('Svilajnac', 571.98);
insert into city (name, population) values ('El Monte', 124.01);
insert into city (name, population) values ('Ogod', 539.79);
insert into city (name, population) values ('Sugito', 131.2);
insert into city (name, population) values ('Pelópion', 863.62);
insert into city (name, population) values ('Mongo', 58.58);
insert into city (name, population) values ('Dayr Sāmit', 930.22);
insert into city (name, population) values ('Ar Ramthā', 333.11);
insert into city (name, population) values ('Tokombere', 352.9);
insert into city (name, population) values ('Tétouan', 298.13);
insert into city (name, population) values ('Temayang', 865.11);
insert into city (name, population) values ('Kiel', 512.85);
insert into city (name, population) values ('Kitakami', 46.0);
insert into city (name, population) values ('Sorren Daya', 580.47);
insert into city (name, population) values ('Cholpon-Ata', 231.93);
insert into city (name, population) values ('El Hatillo', 235.18);
insert into city (name, population) values ('Horní Bečva', 649.36);
insert into city (name, population) values ('Wangcun', 241.59);
insert into city (name, population) values ('Bonga', 669.96);
insert into city (name, population) values ('Santa Maria', 466.88);
insert into city (name, population) values ('Ostružnica', 830.12);
insert into city (name, population) values ('Yampil’', 650.75);
insert into city (name, population) values ('Zhoukou', 585.86);
insert into city (name, population) values ('Mary', 550.25);
insert into city (name, population) values ('Victoria', 918.74);
insert into city (name, population) values ('Makedonski Brod', 425.24);
insert into city (name, population) values ('Littleton', 39.91);
insert into city (name, population) values ('Santa Rosa de Aguán', 99.5);
insert into city (name, population) values ('Tomas', 922.99);
insert into city (name, population) values ('Carcavelos', 298.03);
insert into city (name, population) values ('Imider', 457.25);
insert into city (name, population) values ('Kedungbacin', 981.13);
insert into city (name, population) values ('Lingbeizhou', 916.08);
insert into city (name, population) values ('Karangturi', 214.15);
insert into city (name, population) values ('Rehoboth', 360.82);
insert into city (name, population) values ('Karang Daye', 572.18);
insert into city (name, population) values ('Calceta', 823.82);
insert into city (name, population) values ('Stapleford', 98.03);
insert into city (name, population) values ('Bol’shoy Kamen’', 126.72);
insert into city (name, population) values ('Bacheng', 71.37);
insert into city (name, population) values ('Xibu', 667.09);
insert into city (name, population) values ('Vallauris', 731.2);
insert into city (name, population) values ('Guxi', 324.51);
insert into city (name, population) values ('Cholet', 395.85);
insert into city (name, population) values ('Hexi', 963.65);
insert into city (name, population) values ('Guane', 830.57);
insert into city (name, population) values ('Chengcun', 540.96);
insert into city (name, population) values ('Pensacola', 356.29);
insert into city (name, population) values ('Ḑubāh', 504.27);
insert into city (name, population) values ('Raoyang', 661.38);
insert into city (name, population) values ('Ernestinovo', 864.21);
insert into city (name, population) values ('Sarandi', 631.81);
insert into city (name, population) values ('Passos', 877.19);
insert into city (name, population) values ('Castelões', 154.66);
insert into city (name, population) values ('Sandia', 713.72);
insert into city (name, population) values ('Bum Bum', 762.38);
insert into city (name, population) values ('Jimsar', 885.83);
insert into city (name, population) values ('Kimch’aek-si', 483.9);
insert into city (name, population) values ('Wangong', 751.13);
insert into city (name, population) values ('Luebo', 366.8);
insert into city (name, population) values ('Krajan Timur Mlokorejo', 601.69);
insert into city (name, population) values ('Hedi', 833.32);
insert into city (name, population) values ('Amparafaravola', 385.13);
insert into city (name, population) values ('Tallbīsah', 501.7);
insert into city (name, population) values ('Phnom Penh', 215.95);
insert into city (name, population) values ('Made', 692.32);
insert into city (name, population) values ('Hallsberg', 704.57);
insert into city (name, population) values ('Baimiao', 255.69);
insert into city (name, population) values ('Cijengkol', 177.81);
insert into city (name, population) values ('Tieremu', 877.44);
insert into city (name, population) values ('Saint-Avertin', 183.22);
insert into city (name, population) values ('Maluanluan', 950.77);
insert into city (name, population) values ('Dobre Miasto', 580.92);
insert into city (name, population) values ('Zhixia', 862.28);
insert into city (name, population) values ('Campo Alegre', 227.97);
insert into city (name, population) values ('Frydrychowice', 767.47);
insert into city (name, population) values ('Garoua', 437.58);
insert into city (name, population) values ('Tudela', 710.46);
insert into city (name, population) values ('Las Mesas', 765.49);
insert into city (name, population) values ('Liujiage', 75.98);
insert into city (name, population) values ('Capira', 298.45);
insert into city (name, population) values ('Cambé', 649.65);
insert into city (name, population) values ('Stung Treng', 696.59);
insert into city (name, population) values ('Novyye Cherëmushki', 850.51);
insert into city (name, population) values ('Istres', 831.9);
insert into city (name, population) values ('Färgelanda', 201.35);
insert into city (name, population) values ('Zhouxi', 654.1);
insert into city (name, population) values ('Fray Bentos', 618.38);
insert into city (name, population) values ('Kowo', 865.09);
insert into city (name, population) values ('Ticrapo', 603.03);
insert into city (name, population) values ('Quanzhou', 90.35);
insert into city (name, population) values ('Visby', 192.91);
insert into city (name, population) values ('Synya', 660.99);
insert into city (name, population) values ('Salas', 59.83);
insert into city (name, population) values ('Xiazhai', 54.15);
insert into city (name, population) values ('Har Nur', 316.41);
insert into city (name, population) values ('Prosyana', 344.78);
insert into city (name, population) values ('Maythalūn', 821.48);
insert into city (name, population) values ('Jabon', 813.33);
insert into city (name, population) values ('Konispol', 227.54);
insert into city (name, population) values ('Al ‘Azīzīyah', 535.42);
insert into city (name, population) values ('La Jagua de Ibirico', 94.42);
insert into city (name, population) values ('Niños Heroes', 927.09);
insert into city (name, population) values ('Xarag', 448.56);
insert into city (name, population) values ('Yangqiao', 836.19);
insert into city (name, population) values ('Star’', 118.3);
insert into city (name, population) values ('Tilburg', 635.95);
insert into city (name, population) values ('Doom', 299.37);
insert into city (name, population) values ('Navashino', 64.95);
insert into city (name, population) values ('Himensulan', 411.97);
insert into city (name, population) values ('Acobambilla', 52.54);
insert into city (name, population) values ('Крива Паланка', 9.05);
insert into city (name, population) values ('Roioen', 248.78);
insert into city (name, population) values ('Rungis', 323.38);
insert into city (name, population) values ('Accha', 71.33);
insert into city (name, population) values ('Drosiá', 559.4);
insert into city (name, population) values ('Longping', 39.05);
insert into city (name, population) values ('La Sierpe', 764.39);
insert into city (name, population) values ('Ganxi', 107.71);
insert into city (name, population) values ('Concord', 282.06);
insert into city (name, population) values ('Derviçian', 576.08);
insert into city (name, population) values ('Longra', 749.03);
insert into city (name, population) values ('Copa', 708.81);
insert into city (name, population) values ('Zhutuo', 265.72);
insert into city (name, population) values ('Peuhaq', 719.89);
insert into city (name, population) values ('Buray', 898.0);
insert into city (name, population) values ('Fastiv', 750.5);
insert into city (name, population) values ('Madamba', 511.19);
insert into city (name, population) values ('Água Levada', 432.69);
insert into city (name, population) values ('Boncis', 2.8);
insert into city (name, population) values ('Dublin', 864.41);
insert into city (name, population) values ('Hukou', 988.35);
insert into city (name, population) values ('Bécancour', 797.06);
insert into city (name, population) values ('Sayansk', 626.31);
insert into city (name, population) values ('Youwarou', 690.05);
insert into city (name, population) values ('Watuagung', 656.52);
insert into city (name, population) values ('Miaogou', 962.44);
insert into city (name, population) values ('Aguasay', 948.56);
insert into city (name, population) values ('Landim', 832.47);
insert into city (name, population) values ('Salt Lake City', 67.5);
insert into city (name, population) values ('Xamtay', 241.05);
insert into city (name, population) values ('San Narciso', 980.86);
insert into city (name, population) values ('Bzou', 947.49);
insert into city (name, population) values ('Oxelösund', 308.97);
insert into city (name, population) values ('Tumu', 358.42);
insert into city (name, population) values ('Milówka', 183.6);
insert into city (name, population) values ('Dlemer', 396.54);
insert into city (name, population) values ('Ulbroka', 24.81);
insert into city (name, population) values ('Garešnica', 11.41);
insert into city (name, population) values ('Mawu', 108.86);
insert into city (name, population) values ('Sumpur Kudus', 624.31);
insert into city (name, population) values ('Qintong', 278.99);
insert into city (name, population) values ('Taoyuan', 375.41);
insert into city (name, population) values ('Babakanbungur', 729.25);
insert into city (name, population) values ('Saraktash', 622.51);
insert into city (name, population) values ('Tyler', 622.54);
insert into city (name, population) values ('Genyem', 128.16);
insert into city (name, population) values ('Cherepovets', 317.67);
insert into city (name, population) values ('Konza', 753.51);
insert into city (name, population) values ('Stříbro', 75.44);
insert into city (name, population) values ('Sindangbarang', 393.64);
insert into city (name, population) values ('Guinoaliuan', 343.59);
insert into city (name, population) values ('Parawan', 218.78);
insert into city (name, population) values ('Mantingantengah', 140.77);
insert into city (name, population) values ('Gongyi', 128.28);
insert into city (name, population) values ('Tahe', 774.88);
insert into city (name, population) values ('Harding', 435.27);
insert into city (name, population) values ('Stare Pole', 608.96);
insert into city (name, population) values ('Krasnokamensk', 235.49);
insert into city (name, population) values ('Cibungur', 907.9);
insert into city (name, population) values ('Montesson', 959.22);
